add repository configuration for server packages
centos-opstools/opstools-ansible pull request #26
Opened 2016-09-21 08:49 UTC by mrunge

2016-09-21 10:05 UTC, Spredzy commented
@mrunge I was wondering why creating an extra role for that when this content could be integrated directly within the role they provide repository for. It is actually best practice to do that so roles can actually live on their own without the need to depend on other repo just for that.

It would be strange to have an ElasticSearch role that can't install ElasticSearch itself.

Taking Puppet ElasticSearch module as an example: https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/repo.pp

2016-09-21 12:52 UTC, paramite commented
+1 on having this in each existing role + I would add also global manage_repo which would disable repo creating in case it's necessary.

2016-09-21 12:57 UTC, mrunge commented
Global switch or a per role switch for repositories?

2016-09-21 14:38 UTC, paramite commented
That's a good question. I think that, given the fact we don't differentiate on manage_packages etc., the global switch is enough.

2016-09-21 23:14 UTC, richm approved these changes

2016-09-22 08:29 UTC, mrunge commented
I moved grafana and elasticsearch repo config to their roles. 

kibana/sensu roles are not here yet.

2016-09-22 18:23 UTC, larsks approved these changes

2016-09-22 18:24 UTC, larsks commented on roles/grafana/files/grafana.repo
> +baseurl=https://packagecloud.io/grafana/stable/el/6/$basearch
Shouldn't this be `/el/7` (instead of `/6`)?

2016-09-22 18:29 UTC, larsks commented on roles/grafana/files/grafana.repo
> +sslcacert=/etc/pki/tls/certs/ca-bundle.crt
We shouldn't need to set sslcacert like this (because that's the default).

2016-09-22 18:29 UTC, larsks requested changes

2016-09-22 19:07 UTC, mrunge commented
@larsks nope. I copied those repository definitions from their upstreams. Especially the "6" in elasticsearch repo is valid. What does this tell us about the repo itself?

2016-09-22 19:31 UTC, larsks commented
@mrunge, there is a valid repository at `https://packagecloud.io/grafana/stable/el/7/$basearch`, which is why I was asking.

2016-09-22 19:44 UTC, paramite commented
/el/7/ for Grafana seems more legitimate for me too TBH.

2016-09-26 06:51 UTC, closed without merging

2016-09-26 07:17 UTC, mrunge commented
dammit. Rebase/push gone wrong.