Cleaned oschecks configuration
centos-opstools/opstools-ansible pull request #80
Opened 2016-10-21 17:14 UTC by paramite

- use consistent template naming
- removed (for now) tricky checks
- added subscription granularity for non-api checks

2016-10-21 18:12 UTC, jbadiapa requested changes

2016-10-21 18:12 UTC, jbadiapa commented on roles/sensu/server/defaults/main.yml
> +oscheck_enable_ceilometer_api: true
This parameter has changed, but it is used on roles/sensu/server/templates/sensu_oscheck-check-ceilometer_api.json.j2 I think it should be modified it there too.

The same with all the parameters oscheck_enable_XXXX

2016-10-21 18:12 UTC, jbadiapa commented on roles/sensu/server/defaults/main.yml
> +oscheck_subscribers_ceilometer_api: 'overcloud-ceilometer-api'
As larsks said, I'd rather to set the parameters as:

oscheck_subscribers_ceilometer_api: 
- 'overcloud-ceilometer-api'
- other_supscription

and modified the file sensu_oscheck-check-ceilometer_api.json.j2

"subscribers":  {{ oscheck_subscribers_ceilometer |to_json}},

2016-10-21 18:12 UTC, jbadiapa commented on roles/sensu/server/templates/sensu_oschecks.json.j2
> -        {% include "sensu_oscheck-check-amqp.json.j2" ignore missing %}
What about disable by default instead of deleting it?

2016-10-21 18:12 UTC, jbadiapa commented on roles/sensu/server/templates/sensu_oschecks.json.j2
> -        {% include "sensu_oscheck-pacemaker-host-check.json.j2" ignore missing %}
ditto

2016-10-21 18:49 UTC, larsks requested changes

2016-10-21 18:49 UTC, larsks commented on roles/sensu/server/templates/sensu_oscheck-check-cinder_volume.json.j2
>              "command": "/usr/libexec/openstack-monitoring/checks/oschecks-check_cinder_volume --os-username :::openstack.username|{{ oscheck_default_username }}::: --os-password :::openstack.password
It turns out that `oschecks-check_cinder_volume` doesn't accept the various `--os-...` parameters:

```
usage: oschecks-check_cinder_volume [-h] [--auth_url URL]
                                    [--username username]
                                    [--password password] [--tenant tenant]
                                    [--endpoint_url endpoint_url]
                                    [--endpoint_type endpoint_type]
                                    [--force_delete]
                                    [--api_version api_version]
                                    [--timeout timeout]
                                    [--volume_name volume_name]
                                    [--volume_size volume_size]
                                    [--volume_type volume_type]
                                    [--availability_zone availability_zone]
                                    [--verbose]

```

2016-10-25 07:58 UTC, paramite commented
Closed in favor of #82.

2016-10-25 07:58 UTC, closed without merging