Added more documentation based on the previous one
centos-opstools/opstools-ansible pull request #91
Opened 2016-11-03 09:56 UTC by jbadiapa

It generates a new Documentation.txt file, which has:
- Readme.md
- Actions (Tasks of the role)
- Configuration

And which does not have:
* Integration with tripleo
* Contributing
* License

2016-11-04 08:10 UTC, mrunge approved these changes
cool!

2016-11-05 03:46 UTC, larsks requested changes
I think we should simplify this, and instead of generating a new file and performing a lot of duplicate work, this should _just_ generate the Ansible action documentation, and should generate new section of the `README.md` file named something like "Playbook outline". Does that make sense?

2016-11-05 03:46 UTC, larsks commented on Makefile
> +Documentation.txt: README.md docs/metadata.yml roles/*
I don't understand why we're including `README.md` in another document.  I don't think we need to duplicate the content.

2016-11-05 03:46 UTC, larsks commented on Makefile
> +Documentation.txt: README.md docs/metadata.yml roles/*
Also, depending on `roles/*` is probably not what you want (you want to depend on individual *files* inside the roles directory; see the `DEFAULTS` variable at the top of the `Makefile`).

2016-11-05 03:46 UTC, larsks commented on tools/documentator.py
> +            with open(DEFAULTS) as fd:
This seems to be doing the same thing here as `tools/extract-role-docs.py`...the output of which is already included in `README.md`.

2016-11-15 20:14 UTC, mrunge commented
PLEASE DO NOT MERGE. THIS WILL BREAK REPLICATION.

PLEASE PROPOSE A NEW PATCH VIA GIT REVIEW.

2016-11-16 16:56 UTC, larsks commented
Moved to:

- http://review.rdoproject.org/r/3787
- http://review.rdoproject.org/r/3788
- http://review.rdoproject.org/r/3789

2016-11-16 16:56 UTC, closed without merging